stages:
  Start_Model_Train:
    cmd: python main.py
    deps:
      - src/pipeline/training.py
      - src/components/data_ingestion.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py
    outs:
      - saved_models
      - artifact/*/Data_Ingestion/model.pkl
      - artifact/*/Data_Ingestion/*.csv
      - artifact/*/Data_Transformation/model.pkl
      - artifact/*/Data_Transformation/*.csv
      - artifact/*/Model_Trainer/model.pkl
      - artifact/*/Data_Trainer/*.csv
